# Generated by Django 2.1 on 2019-11-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191111_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='housee.jpg', upload_to='profile_pics'),
        ),
    ]
