# Generated by Django 2.1 on 2019-09-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190928_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='resident',
            new_name='Personel',
        ),
    ]
