# Generated by Django 2.1 on 2019-11-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(default='housee.jpg', upload_to='profile_pics'),
        ),
    ]
