# Generated by Django 2.1 on 2020-01-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
